#!/bin/bash
#
#näitab millised failid on olemas
#loob nende commitid
#
for sisu in `ls .`
do
	if [ -d $sisu ]; then
		echo $sisu
		cd $sisu
		lisa=""
		for failid in `ls .`
		do
			lisa=$lisa"$failid "
		done
		git add $lisa
		git commit -m "$sisu ylesanded"
		cd ..
	fi
done
