#!/bin/bash
#
#sesoonide määramine
#
echo -n "Sisesta kuu nr: "
read kuu
#
if [ $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12 ] ; then
	echo "Praegu on talv"
elif [ $kuu -eq 3 -o $kuu -eq 4 -o $kuu -eq 5 ] ; then
	echo "Praegu on kevad"
elif [ $kuu -eq 6 -o $kuu -eq 7 -o $kuu -eq 8 ] ; then
	echo "Praegu on suvi"
elif [ $kuu -eq 9 -o $kuu -eq 10 -0 $kuu -eq 11 ] ; then
	echo "Praegu on kevad"
fi

