#!/bin/bash
#
#
echo -n "Sisesta reisijate arv:"
read arv
echo -n "Kohtade arv bussis:"
read kohad
#mitu bussi täis ja mitu kohta üle
bussid=$(($arv / $kohad))
#mitu ei mahtunud
maha=$(($arv % $kohad))
#kas on mahajäänuid
if [ $maha -gt 0 ] ; then
	#tellime bussi juurde
	#suurendame bussi arvu 1 võrra
	bussid=$(($bussid + 1))
fi
echo "Kokku busse vaja $bussid"
